###########################################################################################
#   EMAIL SENDER
# Purpose:  gets data from csv file and automate email sending
# Usage:    you should generate an application password in Gmail in order to log in,
#           otherwise authentication failure will occur;
#           no space in message title allowed
#
##########################################################################################

import smtplib
import csv
import pandas

def sendemail(from_addr, to_addr_list, cc_addr_list,
                subject, message, login, password,
                smtpserver = 'smtp.gmail.com:587'):
    header = 'From: %s\n' % from_addr
    header += 'To: %s\n' % ','.join(to_addr_list)
    header += 'Cc: %s\n' % ','.join(cc_addr_list)
    header += 'Subject: %s\n\n' % subject
    message = header + message

    server = smtplib.SMTP(smtpserver)
    server.starttls()
    server.login(login,password)
    problems = server.sendmail(from_addr, to_addr_list, message)
    server.quit()

    return problems

# start
print("Howdy from email-sender program!")

# create/read universal message
msg = 'Hi! \n My name is XYZ and I\'m a President of ABC. \nGreetings, \nXYZ'

# read csv file using pandas library
df = pandas.read_csv('test.csv')

# provide logging data and e-mail subject
my_username = input("Your username (enter full email address): ")
my_password = input("Enter your password (application password generated by Google): ")
my_subject = input("Enter subject for the message: ")

# send emails
persons_num = df.shape[0]
print("Sending mails...")
for person in range(0, persons_num):

    current_row = df.ix[person]
    
    sendemail(from_addr      = my_username,
         to_addr_list   = [current_row[1]],
         cc_addr_list   = [current_row[1]],
         subject        = my_subject,
         message        = msg,
         login          = my_username,
         password       = my_password)
    
    print("Sent mail to %s on address: %s" % (current_row[0], current_row[1]))

print("Finished sending all mails")
